api-base: https://tridung392004--example-vllm-openai-compatible-1-serve.modal.run/v1
api-key: super-secret-key
headless: true
model-api: OPENAI_API_KEY
model-id: Qwen/Qwen2.5-14B-Instruct
model-name: null
model-type: OpenAIServerModel
